---
    php_ppa: php5
    doc_root: /vagrant/domains/
    sys_packages: ["phpmyadmin","git","vim","htop","mc","imagemagick","default-jre","default-jdk"]
    dist: precise
    php_packages: ["php5-curl","php5-common","php5-imagick","php5-mysql","php5-xdebug", "php5-gd"]
    pecl_packages: []
