- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  notify: restart apache
  with_items: php_packages
