---
- hosts: all
  sudo: true
  vars:
    timezone: Europe/Warsaw
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - apache
    - mysql
    - php5-cli
    - php5-apache
    - php-common
    - postinstall
    - app
